@startuml Get All Hotels (GET ALL)

footer Page %page% of %lastpage%
title "Get All Hotels (GET ALL)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:hotels" as routerHotels
participant "<<controllers>>\n:hotels" as controllersHotels
participant "<<model>>\n:Hotel" as modelHotel
database "<<MongoDB>>\n:hotels" as HotelsDatabase

client->server ++:req.get('/api/v1/hotels')
server->routerHotels ++:app.use('/api/v1/hotels',hotels)
routerHotels -> controllersHotels ++:getHotels()
controllersHotels->modelHotel ++:find()
modelHotel ->HotelsDatabase ++: find()
HotelsDatabase --> modelHotel --: hotels
controllersHotels <-- modelHotel --:hotels
controllersHotels->client --:response

@enduml