@startuml Delete Hotel (DELETE)

header Sample VacQ Sequence Diagram
footer Page %page% of %lastpage%
title "Delete Hotel (DELETE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:hotels" as routerHotels
participant "<<middleware>>\n:auth" as authMiddleware
participant "<<service>>\n:jwt" as jwtService
participant "<<controllers>>\n:hotels" as controllersHotels
participant "<<model>>\n:Hotel" as modelHotel
participant "<<model>>\n:User" as modelUser
database "<<MongoDB>>\n:hotels" as HotelsDatabase
database "<<MongoDB>>\n:users" as UsersDatabase

client->server ++:req.delete('/api/v1/hotels/:id')
server->routerHotels ++:app.use('/api/v1/hotels',hotels)

routerHotels -> authMiddleware ++:protect()
authMiddleware -> jwtService ++:verifyToken(token, secret)
authMiddleware <-- jwtService --: decodedId

authMiddleware -> modelUser ++: findById(decodedId)
modelUser -> UsersDatabase ++: findById(decodedId)
modelUser <-- UsersDatabase --: user
authMiddleware <-- modelUser --: req.user
authMiddleware -> routerHotels --: next()
routerHotels -> authMiddleware ++: authorize('admin')
authMiddleware -> routerHotels --: next()

routerHotels -> controllersHotels ++:deleteHotel()
controllersHotels->modelHotel ++:delete(req.params.id)
modelHotel ->HotelsDatabase ++: HotelSchema
HotelsDatabase --> modelHotel --: hotel
controllersHotels <-- modelHotel --:hotel
controllersHotels->client --:response

@enduml